#! /bin/sh
#
# ProxyManager startup script
#
#
### BEGIN INIT INFO
# Provides:          proxymanager
# Required-Start:    $squid3
# Should-Start:      $squid3
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
### END INIT INFO

NAME=daemon
DESC="Proxy manager"
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid

. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

[ -x $DAEMON ] || exit 0

ulimit -n 65535


start () {
        umask 027
        ulimit -n 65535
        cd $cache_dir
        start-stop-daemon --quiet --start \
                --pidfile $PIDFILE \
                --exec $DAEMON  < /dev/null
        return $?
}

stop () {
        PID=`cat $PIDFILE 2>/dev/null`
        start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        if start ; then
                log_end_msg $?
        else
                log_end_msg $?
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        if stop ; then
                log_end_msg $?
        else
                log_end_msg $?
        fi
        ;;
    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        stop
        if start ; then
                log_end_msg $?
        else
                log_end_msg $?
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
        exit 3
        ;;
esac

exit 0
